name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{github.actor}} has triggered the pipeline

on:
  push: 
    branches:
      - 'main'
      
env: 
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  jobs:
    build-infra:
      name: terraform-ci-cd
      run-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v2
        - name: Terraform Init 
          id: init    
          run: 


