name: Terraform CI CD Pipeline for Deploying AWS Resources
run-name: ${{github.actor}} has triggered the pipeline

on:
  push: 
    branches:
      - "main"
      
env: 
  AWS_ACCESS_KEY: ${{secrets.AWS_}}
  AWS_SECRET_ACCESS_KEY:
